apiVersion: apps/v1
kind: Deployment
metadata:
  name: subd
spec:
  selector:
    matchLabels:
      app: subd
  template:
    metadata:
      labels:
        app: subd
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: subd-app
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: amosehiguese/subd:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: subd
spec:
  type: ClusterIP
  selector:
    app: subd
  ports:
  - name: subd
    port: 8080
    targetPort: 8080