# This configuration is for local dev. It makes it possible to use mold
# as the linker for rustc.
#
# To enable
# - install clang
# - install mold https://github.com/rui314/mold into /usr/local/bin/mold
# - add a symbolic link from .cargo -> .cargo-dev 
# via `mkdir -p .cargo && ln -s ../.cargo-templates/dev.toml $_/config.toml`.
#
# If there is an issue, reverting is as simple as deleting .cargo.

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[profile.release]
incremental = true

[profile.fast]
inherits = "release"
opt-level = 0
lto = "off"
codegen-units = 256
