name: "ApiQuery CI"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/apiquerysvc/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/apiquerysvc/**'

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test --junit-xml=junit.xml
          dir: 'src/apiquerysvc'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
