apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.container.name }}
spec:
  type: ClusterIP
  selector: 
    app: {{ .Values.container.name }}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: {{ .Values.container.port }}