environment: production
namespace: subdprod
container:
  name: subd
  port: 8080
  image: 
    repository: amosehiguese/subd
    tag: 1.0.1
request:
  cpu: 200m
  memory: 180Mi
limit:
  cpu: 300m
  memory: 300Mi
replicas: 3