images:
  repository: ghcr.io/amosehiguese/subdomain-scanner
  tag: "main"

networkPolicies:
  create: false

oTelCollector:
  create: false
  name: otelcollector
  port: 14278

apiQuerySvc:
  create: true
  name: apiquerysvc
  port: 50051
  enableTracing: "0"
    

bruteSvc:
  create: false
  name: brutesvc
  port: 50052
  enableTracing: "0"

dnsResolveSvc:
  create: true
  name: dnsresolvesvc
  port: 50053
  enableTracing: "0"

frontend:
  create: true
  name: frontend
  port: 8080
  enableTracing: "0"
  external: false
  
portScanSvc:
  create: true
  name: portscansvc
  port: 50054
  enableTracing: "0"
  resources:

