images:
  repository: gcr.io/amosehiguese/subdomain-scanner
  tag: "0.0.1"

networkPolicies:
  create: false

oTelCollector:
  create: false
  name: otelcollector
  port: 4317


apiQuerySvc:
  create: true
  name: apiquerysvc
  port: 50051
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

bruteSvc:
  create: true
  name: brutesvc
  port: 50052
  resources:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi

dnsResolveSvc:
  create: true
  name: dnsresolvesvc
  port: 50053
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

frontend:
  create: true
  name: frontend
  port: 8080
  enableTracing: "0"
  external: false
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

portScanSvc:
  create: true
  name: portscansvc
  port: 50054
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
