name: "Frontend CI"

on:
  workflow_dispatch:
  workflow_call:
    push:
      branches:
        - main
      paths:
        - 'src/frontend/**'

    pull_request:
      branches:
        - main
      paths:
        - 'src/frontend/**'

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  naming:
    permissions:
      pull-requests: read
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Test
        run: |
          set -euo pipefail
          cd src/frontend
          gotestsum --format=standard-verbose --junitfile=junit.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
