name: "ci-main"
on:
  push:
    branches:
      - main
      - release/*
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

