name: "Subdomain Pipeline"
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    permissions:
      contents: read
      pull-requests: read
      checks: write



